"""create friendships table

Revision ID: 15cb7788ff94
Revises: 5ed4781d51e8
Create Date: 2026-09-14 14:49:05.751795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cb7788ff94'
down_revision: Union[str, Sequence[str], None] = '5ed4781d51e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted')", name='check_friendship_status'),
    sa.CheckConstraint('requester_id <> receiver_id', name='check_friendship_not_self'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requester_id', 'receiver_id')
    )
    op.create_index('ix_friendships_receiver_id', 'friendships', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_friendships_receiver_id', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
