"""create questions and question decoys

Revision ID: 569732866b0c
Revises: ebfce1698dbb
Create Date: 2026-09-11 11:57:08.859750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569732866b0c'
down_revision: Union[str, Sequence[str], None] = 'ebfce1698dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_category_language', 'questions', ['category_id', 'language_code'], unique=False)
    op.create_table('question_decoys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('decoy_text', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'decoy_text', name='uq_question_decoy_text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_decoys')
    op.drop_index('ix_questions_category_language', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
