"""add bluff_vote_received in GamePlayerCategoryResult

Revision ID: bab8d7fe719a
Revises: a1b2c3d4e5f6
Create Date: 2026-10-05 09:12:16.547695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab8d7fe719a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_player_category_results', sa.Column('bluff_votes_received', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_player_category_results', 'bluff_votes_received')
    # ### end Alembic commands ###
